### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by iainrb** [oicr-gsi/provenance#22]
[FileProvenanceFromAnalysisProvenance.java](https://github.com/oicr-gsi/provenance/blob/master/provenance-core/src/main/java/ca/on/oicr/gsi/provenance/model/FileProvenanceFromAnalysisProvenance.java) line 287:

 public Collection<String> getReleatedIusSWIDs() {

"Releated"

**Comment by djcooke** [comment]
Class no longer exists
